DATA_FOLDER: path/to/data
save_path: __DATA_FOLDER__/Results/
emb_folder: __DATA_FOLDER__/Embeddings/
csv_path: __DATA_FOLDER__/slide.csv
patient_id_col: patient_id
slide_id_col: slide_id
aggregate_by_patient: 0
compute_metrics: 1
adata_gt_path: __DATA_FOLDER__/gene_expression.h5ad
use_mibc_detect: 1
